name: "✨ Feature request"
description: Propose an idea for HyperTest
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What user need or pain does this address?
    validations: { required: true }
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Describe the solution/API/UX you have in mind.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: extras
    attributes:
      label: Additional context
