import { sel } from '@hypertest/runner-web';
import { test, expect } from '@playwright/test';

/**
 * Generated by HyperTest Agent
 * Goal: Create a login test
 * Base URL: https://example.com
 *
 * Selector strategy (sel.stable):
 *  - role=<role> name="...": getByRole(role, { name })
 *  - label=... / placeholder=...: getByLabel / getByPlaceholder
 *  - testid=...: [data-testid="..."]
 *  - id/name/css as a last resort
 */

test.describe('HyperTest generated', () => {
  test('smoke', async ({ page }) => {
    test.setTimeout(90_000); // allow time for slow networks

    const BASE = process.env.BASE_URL || 'https://example.com';

    // Navigate with explicit timeout and early failure message
    const resp = await page.goto(BASE, { waitUntil: 'domcontentloaded', timeout: 60_000 });
    expect(resp, `Failed to GET ${BASE}. Check network/DNS/VPN.`).not.toBeNull();

    // Helpers: short (3s) per-action timeouts and visibility guards
    const tryFill = async (selector: string, value: string) => {
      const loc = sel.stable(page, selector);
      const vis = await loc.isVisible({ timeout: 3000 }).catch(() => false);
      if (vis) await loc.fill(value, { timeout: 3000 }).catch(() => {});
    };
    const tryClick = async (selector: string) => {
      const loc = sel.stable(page, selector);
      const vis = await loc.isVisible({ timeout: 3000 }).catch(() => false);
      if (vis) await loc.click({ timeout: 3000 }).catch(() => {});
    };

    await test.step('attempt login (skeleton; adjust selectors)', async () => {
      // Harmless demo action on example.com; ignored if absent
      await tryClick('role=link name="More information"');

      // Example login skeleton (make these match your app; env creds supported)
      // await tryFill('label=Email', process.env.HT_USER ?? 'user@example.com');
      // await tryFill('label=Password', process.env.HT_PASS ?? 'secret');
      // await tryClick('role=button name="Sign in"');
    });

    // Let the page settle; don’t fail the whole test if the page is already closed.
    await page.waitForLoadState('domcontentloaded').catch(() => {});
    if (!page.isClosed()) {
      await expect.soft(page).toHaveURL(/https?:\/\/.*/, { timeout: 20_000 });
    }
  });
});
