name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Enable Corepack
        run: corepack enable

      - name: Use pnpm from packageManager
        run: corepack use pnpm@9

      - name: Install deps
        run: pnpm install --frozen-lockfile

      # Playwright needs browsers in CI
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Lints + builds + runs a tiny headless verify spec
      - name: Verify (lint + build + dry-run)
        run: pnpm verify

      # Generate a spec and run it using artifacts config (HTML report collected)
      - name: Agent smoke (generate + run)
        env:
          BASE_URL: https://example.com
        run: |
          node packages/cli/dist/index.js smoke "CI smoke: https://example.com" \
            --trace=on \
            --reporter=html \
            --base-url="$BASE_URL"

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.node-version }}
          path: playwright-report
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload HyperTest artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: hypertest-artifacts-${{ matrix.node-version }}
          path: artifacts
          if-no-files-found: ignore
          retention-days: 7
