name: CI
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm -r run build
      - name: Run tests (hypertest)
        run: node packages/cli/dist/bin/hypertest.js run --retries 1
        env:
          HYPERTEST_NO_EXIT: "1" # let the workflow continue to artifact upload even on failures
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: hypertest-artifacts
          path: |
            artifacts/**
      - name: Publish JUnit
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: artifacts/junit/results.xml
          check_name: "HyperTest JUnit"
          include_passed: true
